language: php

php: ["5.3", "5.4", "5.5", "5.6", "hhvm", "hhvm-nightly"]

matrix:
    allow_failures: [{"php": "hhvm"}, {"php": "hhvm-nightly"}]
    fast_finish: true

env:
  global:
    - ARCHER_PUBLISH_VERSION=5.6
    - secure: "lu5N3FUQ4L6IMWTfpnjIIuyLFlQblP52a1zsFyWPGtYAvykDIaOrUDP7Pta/L7uucwgNtJN+nXZYAJnevHLbyUPE7x0ScZXH+JgKzNwCbHOrrwDElc5m/lRgOyZ/XlcZyR77D0uU93zxIZNo1TKX8j01KHoRBFrOrQwhk2lW5FE="

install:
  - ./.travis.install

script:
  - ./vendor/bin/archer travis:build
